import { ERPState } from './types';

export const CLEAN_BASELINE_STATE: ERPState = {
  userGroups: [
    { id: 'ug-1', name: 'Administrator', deleted: false },
    { id: 'ug-2', name: 'Project Manager', deleted: false },
    { id: 'ug-3', name: 'Technician', deleted: false },
    { id: 'ug-4', name: 'Viewer', deleted: false },
  ],
  projectStatuses: [
    { id: 'ps-1', name: 'Por iniciar', scale: 1, deleted: false, sort_order: 1 },
    { id: 'ps-2', name: 'Iniciado', scale: 2, deleted: false, sort_order: 2 },
    { id: 'ps-3', name: 'Preparação', scale: 3, deleted: false, sort_order: 3 },
    { id: 'ps-4', name: 'Ensaios', scale: 4, deleted: false, sort_order: 4 },
    { id: 'ps-5', name: 'Implementação', scale: 5, deleted: false, sort_order: 5 },
    { id: 'ps-6', name: 'Concluído', scale: 6, deleted: false, sort_order: 6 },
    { id: 'ps-7', name: 'Em pausa', scale: 7, deleted: false, sort_order: 7 },
    { id: 'ps-8', name: 'Melhorias', scale: 8, deleted: false, sort_order: 8 },
  ],
  projectCategories: [
    { id: 'pc-1', name: 'Internal', deleted: false, sort_order: 1 },
    { id: 'pc-2', name: 'Standard', deleted: false, sort_order: 2 },
    { id: 'pc-3', name: 'Labeling', deleted: false, sort_order: 3 },
    { id: 'pc-4', name: 'Weighing', deleted: false, sort_order: 4 },
    { id: 'pc-5', name: 'Vision/Scanner', deleted: false, sort_order: 5 },
    { id: 'pc-6', name: 'Cross-team support', deleted: false, sort_order: 6 },
    { id: 'pc-7', name: 'Other', deleted: false, sort_order: 7 },
  ],
  projectRisks: [
    { id: 'pr-1', name: 'Low', scale: 1, deleted: false, sort_order: 1 },
    { id: 'pr-2', name: 'Medium', scale: 2, deleted: false, sort_order: 2 },
    { id: 'pr-3', name: 'High', scale: 3, deleted: false, sort_order: 3 },
  ],
  projectPriorities: [
    { id: 'pp-1', name: 'Medium', scale: 1, deleted: false, sort_order: 1 },
    { id: 'pp-2', name: 'High', scale: 2, deleted: false, sort_order: 2 },
    { id: 'pp-3', name: 'Urgent', scale: 3, deleted: false, sort_order: 3 },
  ],
  projectTeams: [
    { id: 'pt-1', name: 'Software', deleted: false, sort_order: 1 },
    { id: 'pt-2', name: 'Installations', deleted: false, sort_order: 2 },
    { id: 'pt-3', name: 'Repairs', deleted: false, sort_order: 3 },
    { id: 'pt-4', name: 'Partner', deleted: false, sort_order: 4 },
  ],
  projectPartners: [
    { id: 'par-1', name: 'JDG', deleted: false, sort_order: 1 },
    { id: 'par-2', name: 'Machserv', deleted: false, sort_order: 2 },
    { id: 'par-3', name: 'Inovasense', deleted: false, sort_order: 3 },
    { id: 'par-4', name: 'TSMaq', deleted: false, sort_order: 4 },
    { id: 'par-5', name: 'Make Industry', deleted: false, sort_order: 5 },
    { id: 'par-6', name: 'Aidomotic', deleted: false, sort_order: 6 },
    { id: 'par-7', name: 'Dibal', deleted: false, sort_order: 7 },
    { id: 'par-8', name: 'FFonseca', deleted: false, sort_order: 8 },
  ],
  taskStatuses: [
    { id: 'ts-1', name: 'Por iniciar', scale: 1, deleted: false, sort_order: 1 },
    { id: 'ts-2', name: 'Em curso', scale: 2, deleted: false, sort_order: 2 },
    { id: 'ts-3', name: 'Completa', scale: 3, deleted: false, sort_order: 3 },
    { id: 'ts-4', name: 'Suspensa', scale: 4, deleted: false, sort_order: 4 },
  ],
  taskTypes: [
    { id: '33333333-3333-3333-3333-333333333301', name: 'Lembrete', scale: 1, deleted: false, sort_order: 1 },
    { id: '33333333-3333-3333-3333-333333333302', name: 'Planeamento/Requisitos', scale: 2, deleted: false, sort_order: 2 },
    { id: '33333333-3333-3333-3333-333333333303', name: 'Preparação', scale: 3, deleted: false, sort_order: 3 },
    { id: '33333333-3333-3333-3333-333333333304', name: 'Instalação', scale: 4, deleted: false, sort_order: 4 },
    { id: '33333333-3333-3333-3333-333333333305', name: 'Reparação', scale: 5, deleted: false, sort_order: 5 },
    { id: '33333333-3333-3333-3333-333333333306', name: 'Formação', scale: 6, deleted: false, sort_order: 6 },
    { id: '33333333-3333-3333-3333-333333333307', name: 'Outro', scale: 7, deleted: false, sort_order: 7 },
  ],
  riskCategories: [
    { id: 'rc-1', name: 'Técnica / Engenharia', deleted: false, sort_order: 0 },
    { id: 'rc-2', name: 'Fornecedores / Materiais', deleted: false, sort_order: 1 },
    { id: 'rc-3', name: 'Prazo / Planeamento', deleted: false, sort_order: 2 },
    { id: 'rc-4', name: 'Cliente / Âmbito', deleted: false, sort_order: 3 },
    { id: 'rc-5', name: 'Financeiro / Custo', deleted: false, sort_order: 4 },
    { id: 'rc-6', name: 'Segurança / Conformidade', deleted: false, sort_order: 5 },
  ],
  riskStatuses: [
    { id: 'rs-1', name: 'Identificado', deleted: false, sort_order: 0 },
    { id: 'rs-2', name: 'Em avaliação', deleted: false, sort_order: 1 },
    { id: 'rs-3', name: 'Mitigação em curso', deleted: false, sort_order: 2 },
    { id: 'rs-4', name: 'Monitorização', deleted: false, sort_order: 3 },
    { id: 'rs-5', name: 'Fechado', deleted: false, sort_order: 4 },
    { id: 'rs-6', name: 'Incidente', deleted: false, sort_order: 5 },
  ],
  riskPriorities: [
    { id: 'rp-1', name: 'Baixa', scale: 1, deleted: false, sort_order: 0 },
    { id: 'rp-2', name: 'Média', scale: 2, deleted: false, sort_order: 1 },
    { id: 'rp-3', name: 'Alta', scale: 3, deleted: false, sort_order: 2 },
    { id: 'rp-4', name: 'Crítica', scale: 4, deleted: false, sort_order: 3 },
  ],
  projectRiskItems: [],
  appConfig: {
    appName: 'Gestão de Projetos e Planeamento',
    appDescription: 'Plataforma integrada de planeamento, orçamentação e gestão de projetos.',
    footerText: '© 2026 Gestão de projetos e planeamento. Todos os direitos reservados.',
    logo: '',
    footerCopyrightText: '© 2026 Gestão de projetos e planeamento. Todos os direitos reservados.',
    logoImagePath: '',
    theme: 'default',
    salesRepGroupIds: [],
    projManagerGroupIds: [],
    fieldManagerGroupIds: [],
    taskAssigneeGroupIds: [],
  },
  // STRICT ZERO-DATA POLICY: absolutely no mock projects, clients, tasks or users
  users: [],
  clients: [],
  materials: [],
  projectMaterials: [],
  projects: [],
  tasks: [],
  comments: [],
  userAbsences: [],
  quotes: [],
  billOfMaterials: [],
  equipmentList: [],
  specialDays: [],
  defaultTasks: [],
  automationRules: [],
  notifications: [],
  tickets: [],
  ticketStatuses: [
    { id: 'tks-1', name: 'Validação Pendente', scale: 1, deleted: false, sort_order: 1 },
    { id: 'tks-2', name: 'Aberto', scale: 2, deleted: false, sort_order: 2 },
    { id: 'tks-3', name: 'Em Análise', scale: 3, deleted: false, sort_order: 3 },
    { id: 'tks-4', name: 'Convertido em Tarefa', scale: 4, deleted: false, sort_order: 4 },
    { id: 'tks-5', name: 'Resolvido', scale: 5, deleted: false, sort_order: 5 },
    { id: 'tks-6', name: 'Cancelado', scale: 6, deleted: false, sort_order: 6 },
  ]
};
